version: '2'
services:
  web:
    build: ./
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:extml@mysql:3306
      MYSQL_ROOT_PASSWORD: 'extml'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    links:
      - mysql
  mysql:
    image: mysql:5.7.17
    environment:
       MYSQL_ROOT_PASSWORD: 'extml'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
